"use strict";
let greet = "Hello, World!";
console.log(greet);
console.log("Whatup fuckers, this is a test file.");
let v = 1;
let y;
y = v + 1;
console.log(y);
var userInput = prompt("Enter a number:");
console.log;
